name: Deploy to server

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Puedes cambiar esto por la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          server-dir: /prueba-ftp/
